### ISSUE TITLE
Whitespace is lost from titles that contain formatting markup

### ISSUE THREAD

**Issue by hubgit** [CrossRef/rest-api-doc#112] opened 2016-03-17 17:23 UTC
e.g. https://api.crossref.org/works/10.7717/peerj.1698

The XML deposited was `<title>NeisseriaBase: a specialised <i>Neisseria</i> genomic resource and analysis platform</title>`, but the title in the JSON is `NeisseriaBase: a specialisedNeisseriagenomic resource and analysis platform`.

Even if the formatting gets lost in the JSON version (it would be nice to have it preserved in some way, perhaps in a `title-html` or `title-markdown` field), the whitespace around words should be preserved.

**Comment by hubgit** [comment] 2016-03-17 17:24
Another example, from a different publisher: http://api.crossref.org/works/10.7554/elife.13715

**Comment by hubgit** [comment] 2016-06-14 08:28
This is still problematic for API users, who receive (and hence display) incorrect titles.

![screen shot 2016-06-14 at 09 27 02](https://cloud.githubusercontent.com/assets/14294/16036104/46b5b6d0-3212-11e6-9112-9fd102056351.png)

**Comment by jenniferlin15** [comment] 2018-03-19 20:40
Summary: 
The proposed solution is to create a second title field that preserves the markup. We also have article titles rendered with MathML which are not represented properly in the REST API (https://github.com/CrossRef/rest-api-doc/issues/325). We can address both issues if we provide plain title and inline XML title versions. 

Description:
1) The plain title should insert white space where any markup tag was stripped.
2) We insert the XML title and tag it as title-XML wherever there is any additional tagging. This includes: a) there is HTML formatting found in the title or b) there is MathML tagging <mml:mi>.
3) If there is no additional tagging found in the input XML, the system does not add the XML title into the JSON response. 

We will only insert the title-XML element for the small fraction of works that need it. This will help us manage the index size as well as prevent redundancy in the data.

**Comment by gbilder** [comment] 2018-03-20 06:19
Note that there are two issues here:

1. A simple bug: The process of stripping the markup in the title is messing up the whitespace- it should read:

> "NeisseriaBase: a specialised Neisseria genomic resource and analysis platform"

2. A feature request: For an element that preserves the title as-deposited, including so-called `face-markup`.  I am reluctant to call this element `title-XML` because the name is misleading- the element doesn't allow arbitrary xml (otherwise we'd just have used `CDATA`). It only allows a subset of elements that our schema calls `face-markup`. So I would suggest we call the element either `title-face-markup` or `title-markup`.

But this brings raises another point, the return format of the API is a superset of CiteProc JSON. Some tools (e.g. Zotero) are able to make use of *some* markup in titles (https://www.zotero.org/support/kb/rich_text_bibliography). If we decide to proceed as described above (continue to strip markup from the `title` element and include a different title element with the original marked-up text), then Zotero (and many other tools based on Zotero's citeproc-js) will not be able take advantage of the markup that is included in the title. So another option would be to:

1. Keep the Zotero subset of markup in the title element, but strip items not supported by Zotero
2. Create a another element that preserves the title with full Crossref `face-markup`.

**Comment by ckoscher** [comment] 2018-03-20 12:55
The XML needed in this extra/new title field is not just face markup, it included MathML embedded in the title.   I would not consider MathML as being face-markup.

**Comment by jenniferlin15** [comment] 2018-03-20 17:02
Having an ongoing discussion on this. Here's where we're at so far:

1. Existing title field will preserve citeproc markup. Other XML components will be removed and we need to ensure that it reads correctly when this happens.

2. We insert full XML for the title if there is XML found in the title. We are still deciding on tag name. This includes: a) there is HTML formatting found in the title or b) there is MathML tagging mml:mi.
If there is no additional tagging found in the input XML, the field is left as an empty string.

**Comment by jenniferlin15** [comment] 2018-03-26 16:10
Okay, reached a decision as follows:
1. Existing title field will preserve all markup included in citeproc. All other XML components will be removed and we need to ensure that it reads correctly when this happens. The title should have white space inserted where markup tags are found (i.e., before and after the word(s) where markup is applied) in the event that we are stripping it out (not included in citeproc). See example below.

Input example
<title>NeisseriaBase: a specialised <i>Neisseria</i> genomic resource and analysis platform</title>

Output example
"title": [ "NeisseriaBase: a specialised Neisseria genomic resource and analysis platform" ], "title-XML": [ "NeisseriaBase: a specialised <i>Neisseria</i> genomic resource and analysis platform" ]

2. We will create a entry that preserves the XML for all records across all content types, regardless of whether it has markup in the title. The content for this entry will duplicate the as-deposited XML title into a JSON field called 'title-xml'.  This field will be part of the JSON document but not an indexed field in Solr. 

The field will contain XML text as follows
a) content must have the following opening tag:
<title xmlns="http://www.crossref.org/xschema/1.1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:mml="http://www.w3.org/1998/Math/MathML" 
xsi:schemaLocation="http://www.crossref.org/xschema/1.1 http://doi.crossref.org/schemas/unixref1.1.xsd">
b) content will have the closing tag:
</title>
c) contents between opening and closing tag will be the contents of the <titles><title> tag from the UNIXSD XML. This covers all content types.

Notes:
The content  may contain multiple occurrences of the namespace declaration form MathML. These should be removed to reduce sizing.
xmlns:mml="http://www.w3.org/1998/Math/MathML"

For example, see:
http://doi.crossref.org/search/doi?pid=ckoscher@crossref.org&format=unixsd&doi=10.1103/PhysRevLett.112.102502

**Comment by afandian** [comment] 2018-03-27 15:19
Here's a real input XML:
```
                ```<titles>
                  <title>
                    NeisseriaBase: a specialised
                    <i>Neisseria</i>
                    genomic resource and analysis platform
                  </title>
                </titles>
```

This could be rendered two ways:

```
title-xml: ["NeisseriaBase: a specialised\n                    <i>Neisseria</i>\n                    genomic resource and analysis platform"]
```

or perhaps:

```
title-xml: ["NeisseriaBase: a specialised\n <i>Neisseria</i>\n genomic resource and analysis platform"]
````

**Comment by afandian** [comment] 2018-03-28 14:21
Ok, here's an agreed spec for this ticket. We're not involving #325 at this stage, just fixing the original problem.

The following input:

```
<titles>
                   <title>
                                      NeisseriaBase: a specialised
                                      <i>Neisseria</i>
                                      genomic resource and analysis platform
                   </title>
</titles>
```

Should result in the following output:
```
"title": [ "NeisseriaBase: a specialised Neisseria genomic resource and analysis platform"]
```

All XML markup should be removed. If there are whitespaces between subsequent words, e.g. between "specialised" and "Neisseria" and between "Neisseria" and "genomic" there should be a space between the words.

**Comment by jenniferlin15** [comment] 2018-03-28 14:28
Agree with the spec above. This reflects the final group decision we just made.

**Comment by gbilder** [comment] 2018-03-28 14:53
Agree with above.

**Comment by ckoscher** [comment] 2018-03-29 12:55
White space problem is caused by the pusher (code that posts XML to the indexer) removing new lines inside content.

**Comment by jenniferlin15** [comment] 2018-04-12 20:39
@pdavis8 please ask publisher to deposit with correct spacing

**Comment by pdavis8** [comment] 2018-06-29 08:06
Publisher contacted and chased to update title. Hopefully this will be updated soon. Closing ticket for now.

**Closed by pdavis8** 2018-06-29 08:06 UTC
Labels: doi metadata, ready
