### ISSUE TITLE
Wiley API links are not working.

### ISSUE THREAD

**Issue by selcukorkmaz** [CrossRef/rest-api-doc#96] opened 2015-12-18 00:39 UTC
I am trying to get the full-text links for Wiley journals using CrossRef API. But, the Wiley links are not working. It simply gives blank page for each link.

http://api.wiley.com/onlinelibrary/tdm/v1/articles/10.1002%2Fcbic.201300351
http://api.wiley.com/onlinelibrary/tdm/v1/articles/10.1002%2Fanie.201306302
http://api.wiley.com/onlinelibrary/tdm/v1/articles/10.1002%2Fcmdc.201300274

Is this because of CrossRef API or Wiley API?

**Comment by sckott** [comment] 2015-12-18 00:47
Wiley gives back no content when you aren't authorized, look at the headers in the request. here's an example, which should give you a pdf if you have the right auth:

```
curl -v -L \
    -H "CR-Clickthrough-Client-Token: <your Crossref TDM click through token>" \
    "http://api.wiley.com/onlinelibrary/tdm/v1/articles/10.1002%2Fcbic.201300351" > out.pdf
```

Note that they don't provide XML, so only pdf available. 

See https://apps.crossref.org/clickthrough/researchers for getting a click through token

**Comment by selcukorkmaz** [comment] 2015-12-18 01:18
Thanks @sckott! That solved my Wiley problem. 

But when I try this:
```
curl -v -L -H "CR-Clickthrough-Client-Token: <my Crossref TDM click through token>" 
"http://api.elsevier.com/content/article/PII:S0022283615003460?httpAccept=text/xml" > out.xml
```
I am getting the following error for some Elsevier articles:

```
<service-error>
	<status>
		<statusCode>ENTITLEMENTS_ERROR</statusCode>
		<statusText>Insufficient entitlements for use with the submitted access key</statusText>
	</status>
</service-error>
```

**Comment by sckott** [comment] 2015-12-18 01:35
Elsevier checks IP addresses (Wiley does too), so you/your institution has to have access to the article. If they do, and you're off campus, you can VPN in (that's what I do).

**Comment by selcukorkmaz** [comment] 2015-12-18 01:46
Actually, I am on the campus now (UCSD), and I can access the full text article using Elsevier website. But no luck with the API link.

**Comment by sckott** [comment] 2015-12-18 01:54
What do the headers look like? They should have some  info

**Comment by selcukorkmaz** [comment] 2015-12-18 01:56
This is the full output I get:
```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 198.185.19.118...
* Connected to api.elsevier.com (198.185.19.118) port 80 (#0)
> GET /content/article/PII:S0022283607007152?httpAccept=text/xml HTTP/1.1
> Host: api.elsevier.com
> User-Agent: curl/7.43.0
> Accept: */*
> CR-Clickthrough-Client-Token: cd20d4bf-e325075a-41edf027-5baecf07
> 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0< HTTP/1.1 403 Forbidden
< Server: api.elsevier.com  9999
< X-ELS-Status: ENTITLEMENTS_ERROR(Insufficient entitlements for use with the submitted access key)
< X-ELS-ReqId: 0000015183b6749d-36ac5fe
< CR-Clickthrough-Client-Token: cd20d4bf-e325075a-41edf027-5baecf07
< X-ELS-TransId: f7c116f6-72ac-4c02-bb69-afd49e754033
< Allow: HEAD,GET
< Content-Type: text/xml;charset=UTF-8
< Content-Length: 190
< Date: Fri, 18 Dec 2015 01:51:59 GMT
< X-RE-Ref: 1 1652201404
< P3P: CP="IDC DSP LAW ADM DEV TAI PSA PSD IVA IVD CON HIS TEL OUR DEL SAM OTR IND OTC"
< 
{ [190 bytes data]
100   190  100   190    0     0     82      0  0:00:02  0:00:02 --:--:--    82
* Connection #0 to host api.elsevier.com left intact
```

**Comment by sckott** [comment] 2015-12-18 02:04
(you should remove your token, unless that's a fake one)

**Comment by selcukorkmaz** [comment] 2015-12-18 02:06
I renewed it!

**Comment by sckott** [comment] 2015-12-18 02:11
i received the entitlements error a while back, and Elsevier told me:

>  If you receive an entitlements error on your requests it is likely due to the fact the IP address of the requestor is not associated with an account entitled to access the document.

I'll ask about this and get back to you

**Comment by sckott** [comment] 2015-12-19 00:43
no response yet, they may be on vacation now

**Comment by selcukorkmaz** [comment] 2015-12-19 02:16
I used the Elsevier API key alongside with the CR-Clickthrough-Client-Token. Now I am getting the abstracts instead of the entitlements error. But, I can't still access the full-text article, even though I am on the campus and I can access the full text article via Elsevier website.
```
curl -v "CR-Clickthrough-Client-Token: <my Crossref TDM click through token>" 
-k "http://api.elsevier.com/content/article/PII:S0968089609010761?APIKey=
[my Elsevier API key]&httpAccept=text/xml" > out.xml
```

**Comment by kjw** [comment] 2015-12-19 19:28
Hi, we will help to investigate this, but this is probably not the best place to raise issues about publisher platforms. E-mailing support@crossref.org may help, as well as speaking directly to the publishers.

I hope you do not mind if I close this bug down, as really it is not a bug within the REST API.

**Closed by kjw** 2015-12-19 19:28 UTC

**Comment by kjw** [comment] 2015-12-19 19:30
Ping @afandian in case this is an issue with the TDM click-through service tokens rather than an issue with publishers' usage of those tokens.
