### ISSUE TITLE
No error on /journals with offset > 10000

### ISSUE THREAD

**Issue by danielopitz** [CrossRef/rest-api-doc#208] opened 2017-05-11 11:09 UTC
Hi again!

There is a slight problem with the journals API (`/journals` endpoint). It doesn't work with the `cursor` parameter (Solr cursor) and the only option to get more than 1.000 entries is to use `rows` parameter in combination with the `offset` parameter.

As mentioned in the documentation, the max. value of `offset` is 10.000, so it is not possible to get more than 11.000 results (max `rows` is 1.000), but the endpoint doesn't return an error if `offset` is larger than 10.000. Instead results for `offset=10000&rows=x` are returned leading to a huge amount of duplicated entries for users not knowing of this problem and trying to get the whole journals collection.

I haven't tested it for other endpoints.

Test case:
Compare data returned from both API calls, it should be different:
http://api.crossref.org/journals?rows=1&offset=10000
http://api.crossref.org/journals?rows=1&offset=20000

Result:
Returned data is the same.

Thanks!

**Comment by kjw** [comment] 2017-05-11 17:17
Duplicate of #179 . Fix is due to be deployed in the next release, in the next couple of days.

**Closed by kjw** 2017-05-11 17:17 UTC
