### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by vamshi9** [CrossRef/rest-api-doc#491] opened 2020-07-09 06:58 UTC
Hi,

I am trying to connect to this API end point   `https://api.crossref.org/works?query=vamshi` from my local node server, it is throwing the Internal server error. I was just playing around it. Do we have to go through any set up apart from hitting? or am I passing wrong query params?

Thanks!

**Comment by ppolischuk** [comment] 2020-07-13 19:26
Can you try again? It could have been a transient error, as the query works fine for me. Otherwise we'd need a bit more info on your setup and what you're trying to accomplish. cc @markwoodhall

**Comment by gmatv** [comment] 2020-07-17 05:27
I can confirm that we regularily get "500 (Internal Server Error)" in our production environment. Same request later can finish successully. Here is the recent time list in UTC when we got it.

2020-07-17 05:06:01.543
2020-07-17 02:50:03.550
2020-07-17 02:49:59.647
2020-07-17 02:40:41.523
2020-07-17 00:55:20.030
2020-07-17 00:55:16.030
2020-07-17 00:24:33.507
2020-07-16 23:49:46.157
2020-07-16 23:05:38.747
2020-07-16 21:46:39.970
2020-07-16 20:42:16.460
2020-07-16 20:12:16.547
2020-07-16 20:07:34.333
2020-07-16 18:59:38.930
2020-07-16 18:33:09.737
2020-07-16 17:39:22.153
2020-07-16 17:20:26.637
2020-07-16 16:19:23.540
2020-07-16 16:05:39.220
2020-07-16 16:00:52.027
2020-07-16 15:08:38.030
2020-07-16 14:52:07.727
2020-07-16 14:41:29.943
2020-07-16 12:36:11.853
2020-07-16 12:36:07.947
2020-07-16 12:35:46.853
2020-07-16 12:11:05.343
2020-07-16 11:08:09.850
2020-07-16 10:48:58.560
2020-07-16 10:15:55.627
2020-07-16 09:16:47.037
2020-07-16 08:26:21.553
2020-07-16 08:12:34.937
2020-07-16 06:46:15.043
2020-07-16 06:27:05.730
2020-07-16 06:05:53.870
2020-07-16 05:50:02.133
2020-07-16 04:51:02.150
2020-07-16 04:11:32.247
2020-07-16 04:11:27.137
2020-07-16 00:11:48.747

**Comment by savagematt** [comment] 2020-08-09 13:14
Same issue. Interestingly I can only reproduce this using node.

Curl, python requests, apache http client on the jvm, and `XmlHttpRequest` all seem to work fine for identical urls.

I can't see anything in the request that looks unusual:

```
{
      path: '/works/10.1136/jnnp.74.12.1662',
      method: 'GET',
      headers: {
        Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.19.2'
      },
      agent: undefined,
      agents: { http: undefined, https: undefined },
      auth: undefined,
      hostname: 'api.crossref.org',
      port: null
    }
```

I'm on node `12.18.0`. I've tried both axios `0.19.2` and simple node requests, with and without https, and with and without `mailto` in the url, with and without a `Host` header.

**Comment by savagematt** [comment] 2020-08-09 13:51
Huh. This returns 200:

```
                https.get("https://api.crossref.org/works/10.1038/s41586-020-2012-7", res => {
                    console.log(res);
                })
```

This returns 500:

```
                https.request({method:"GET","hostname":"api.crossref.org", path:"/works/10.1038/s41586-020-2012-7", res => {
                    console.log(res);
                })
```

**Comment by gbilder** [comment] 2020-08-11 08:45
I spelunked through our logs and discovered that back in 2017 we had a big problem with somebody using Axios and that we ham-handedly blocked the user agent. We will remove this block, but in the mean-time, you  can simply change the user agent (good practice anyway- see the "etiquette" section of the API docs) and your example will work:

```javascript
var axios = require('axios');

// This get blocked.
var config = {
  method: 'get',
  url: 'https://api.crossref.org/works/10.1038/s41586-020-2012-7',
  headers: {'User-Agent': 'axios/0.19.2'}
};

// This works.
var config = {
    method: 'get',
    url: 'https://api.crossref.org/works/10.1038/s41586-020-2012-7',
    headers: {'User-Agent': 'savagematt; (https://github.com/savagematt)'}
  };

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```

We're really sorry you spent so much time debugging this.

**Comment by thewilkybarkid** [comment] 2020-08-13 13:23
We've just run into the same problem while investigating what queries we need to run.

No problem to send a useful User-Agent, but a 500 status code was highly confusing...

**Comment by pdavis8** [comment] 2021-07-02 14:57
I am closing this ticket here as it looks like a resolution was found. If there are more issues can you log them here please: https://gitlab.com/crossref/issues/-/issues

Thanks you

**Closed by pdavis8** 2021-07-02 14:57 UTC
