### ISSUE TITLE
Works route: facets supported (publisher-name versus member)

### ISSUE THREAD

**Issue by ioverka** [CrossRef/rest-api-doc#85] opened 2015-11-13 18:56 UTC
```
Valid facets for this route are: *, affiliation, funder-name, funder-doi, orcid, 
container-title, assertion, archive, update-type, issn, published, source, 
type-name, publisher-name, license, category-name, assertion-group
```

Is "publisher-name" identical to the "primary-name" of the member? Why is member/member-id not supported as facet?

**Comment by kjw** [comment] 2016-02-06 19:52
Good question. Will add member id as a facet.

**Comment by ioverka** [comment] 2016-04-12 09:44
Sorry, I just stumbled about the first part of my question once again: Is the publisher value provided for a particular work mapped from "primary-name" of the corresponding member?

E.g. in this case:
http://api.crossref.org/works/10.1186/s40575-016-0032-2 (article by Biomed Central)

we rather would like to see the name of the imprint:
 `"publisher":"Springer (Biomed Central Ltd.)"`

instead of the primary name of the member:
`"publisher":"Springer Science + Business Media"`

**Comment by ioverka** [comment] 2016-04-13 17:09
BTW: For the journal the article was published in, I find:
`"publisher":"Springer (Biomed Central Ltd.)"`

see http://api.crossref.org/journals/2052-6687 

This is how I expect it to be for the work as well.

**Comment by kmeddings** [comment] 2017-05-03 12:41
Closing as duplicate of 127

**Closed by kmeddings** 2017-05-03 12:41 UTC
Labels: enhancement, question

**Comment by ioverka** [comment] 2017-05-03 19:42
Sorry, but has member-id been added as facet option? I still see:

` ...Valid facets for this route are: *, affiliation, funder-name, funder-doi, orcid, container-title, assertion, archive, update-type, issn, published, source, type-name, publisher-name, license, category-name, relation-type, assertion-group`

see http://api.crossref.org/works?facet=x

BTW: very impressed by CrossRef's issue spring-clean ;)
