### ISSUE TITLE
FFFD - � replacement character in "works" API results

### ISSUE THREAD

**Issue by miku** [CrossRef/rest-api-doc#67] opened 2015-07-07 17:07 UTC
First, thanks making the crossref API available. We find it really useful and encountered only few problems so far.

However, from the _works_ API, we receive documents which contain the unicode replacement character, `FFFD`.

> The replacement character � (often a black diamond with a white question mark) is a symbol found in the Unicode standard at codepoint U+FFFD in the Specials table. It is used to indicate problems when a system is not able to render a stream of data to a correct symbol. It is most commonly seen when a font does not contain a character, but is also seen when the data is invalid and does not match any character (https://en.wikipedia.org/wiki/Specials_%28Unicode_block%29#Replacement_character).

There are currently a large number (around 500000, we believe) of works, that seem to contain this character - mainly in titles or author names. Here's an example (the family name of one of the authors - "M�ller" - is garbled):

``` sh
$ curl -s http://api.crossref.org/works/10.1007/s10049-004-0652-z
{
  "status": "ok",
  "message-type": "work",
  "message-version": "1.0.0",
  "message": {
    "subtitle": [],
    "subject": [
      "Emergency Medicine"
    ],
    "issued": {
      "date-parts": [
        [
          2004,
          5
        ]
      ]
    },
    "score": 1,
    "prefix": "http://id.crossref.org/prefix/10.1007",
    "author": [
      {
        "affiliation": [],
        "family": "Frank",
        "given": "M.D."
      },
      {
        "affiliation": [],
        "family": "M�ller",
        "given": "M."
      },
      {
        "affiliation": [],
        "family": "Weber",
        "given": "S."
      },
      {
        "affiliation": [],
        "family": "Haacke",
        "given": "V."
      },
      {
        "affiliation": [],
        "family": "Aschenbrenner",
        "given": "U."
      },
      {
        "affiliation": [],
        "family": "Biewener",
        "given": "A."
      },
      {
        "affiliation": [],
        "family": "Heller",
        "given": "A."
      },
      {
        "affiliation": [],
        "family": "Koch",
        "given": "T."
      }
    ],
    "container-title": [
      "Notfall & Rettungsmedizin"
    ],
    "reference-count": 0,
    "deposited": {
      "date-parts": [
        [
          2013,
          3,
          27
        ]
      ],
      "timestamp": 1364342400000
    },
    "issue": "3",
    "title": [
      "Dresden"
    ],
    "alternative-id": [
      "652"
    ],
    "type": "journal-article",
    "DOI": "10.1007/s10049-004-0652-z",
    "ISSN": [
      "1434-6222",
      "1436-0578"
    ],
    "URL": "http://dx.doi.org/10.1007/s10049-004-0652-z",
    "source": "CrossRef",
    "publisher": "Springer Science + Business Media",
    "indexed": {
      "date-parts": [
        [
          2015,
          6,
          8
        ]
      ],
      "timestamp": 1433749820569
    },
    "volume": "7",
    "member": "http://id.crossref.org/member/297"
  }
}
```

Since the replacement character naturally does not indicate, which character it replaces, it is hard to impossible to correct this on the client side.

Here are a few more example:
- http://api.crossref.org/works/10.1002/14651858.cd000179
  
  >  ... "family":"G\ufffd\ufffdlmezoglu" ...
- http://api.crossref.org/works/10.1260/095745601320439471
  
  > ... "title":["UK industry spends \ufffd4 billion on environmental protection"] ...
- http://api.crossref.org/works/10.1111/j.1399-0039.2006.00776.x
  
  > ... "family":"M\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdndez","given":"R."} ...

I can share a full list of examples, if it would be helpful.

**Comment by ckoscher** [comment] 2015-07-09 14:08
We will be scanning the entire metadata set looking for a variety of 
things, one of which will be bad characters. I expect to get this done 
in August.  We will then contact publishers to fix and redeposit.

Chuck

**Comment by miku** [comment] 2015-07-09 14:11
That's great to hear, thanks for looking into this.

**Comment by kjw** [comment] 2015-10-30 18:29
@ckoscher Did anything come of this?

**Comment by ckoscher** [comment] 2015-11-02 11:52
The process has been run, once anyway.  Need to look over the output.

**Comment by miku** [comment] 2015-11-02 12:00
The output of the linked example from my original post seem to be still broken:

http://api.crossref.org/works/10.1002/14651858.cd000179

> ... "family":"G\ufffd\ufffdlmezoglu" ...

http://api.crossref.org/works/10.1260/095745601320439471

> ... "title":["UK industry spends \ufffd4 billion on environmental protection"] ...

http://api.crossref.org/works/10.1111/j.1399-0039.2006.00776.x

> ... "family":"M\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdndez","given":"R."} ...

**Comment by chrode** [comment] 2015-12-14 15:07
@ckoscher Did you see the comment by @miku? This being fix would be awesome.

**Comment by ckoscher** [comment] 2015-12-14 15:43
We have a process in development to fix these problems. This task is progressing, but does have a way to go (especially with the Holidays upon us). Middle of January is a target

Chuck

**Comment by kjw** [comment] 2016-02-06 19:54
@ckoscher Is there an update on this?

**Comment by ckoscher** [comment] 2016-02-18 14:00
We've scanned our metadata and have built lists of DOIs having problems which are going to be sent to the publishers. They'll have to redeposit the DOIs to correct the problems.  The larger publishers have already been contacted, we'll have to follow up to make sure they're attending to the problem.

**Comment by gbilder** [comment] 2016-02-18 14:08
Cool. How many DOIs effected? How many publishers?

**Comment by ckoscher** [comment] 2016-02-18 14:19
About 10 million DOIs,  ~2200 publishers

**Comment by miku** [comment] 2016-02-18 15:12
Thanks for the effort, @ckoscher, we are certainly still interested in this.

**Comment by kjw** [comment] 2016-05-26 09:49
@ckoscher - Have these 10 million DOIs with invalid feed characters been fixed?

**Comment by ckoscher** [comment] 2016-05-26 12:21
We ran a scan that identified the errors and then notified the publisher with a list of offending DOIs.  Now awaiting publisher responses.
Will likely rerun the scan  soon (later in June)

**Comment by AlexHenderson** [comment] 2016-11-07 15:52
Did any of the publishers respond?

**Comment by kmeddings** [comment] 2016-11-08 14:39
Looks as though this could usefully be re-run @ckoscher ?

**Comment by gbilder** [comment] 2017-04-28 11:54
@ckoscher Yes. An update here would be good. Have we done all we can and are just waiting on publishers? If so, ten we should close this and perhaps add this info to a FAQ about our metadata.

**Comment by ckoscher** [comment] 2018-06-21 16:13
We ran our tool and fixed what we could.  We reached out to the effected publishers and asked them to redeposit, we have no confirmation that they did or did not.

Re-running the tool is not necessary since the root cause of the problem was corrected some time ago.

At this point whatever bad data is in the system will only be correct if the publisher redeposits.

**Comment by ppolischuk** [comment] 2018-06-21 16:36
Closing per Chuck's comment above.

**Closed by ppolischuk** 2018-06-21 16:36 UTC
Labels: doi metadata, ready
